apiVersion: v1
data:
  CUSTOMER_MANAGEMENT_API_URL: http://customer-management-service:8001
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:29092
  KAFKA_GROUP_ID: customer-management-group
  KAFKA_TOPIC: purchases
  LOG_LEVEL: INFO
  MONGODB_COLLECTION: purchases
  MONGODB_DB_NAME: ecommerce
  MONGODB_URI: mongodb://mongodb-service:27017
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CUSTOMER_MANAGEMENT_API_URL":"http://customer-management-service:8001","KAFKA_BOOTSTRAP_SERVERS":"kafka-service:9092","KAFKA_GROUP_ID":"customer-management-group","KAFKA_TOPIC":"purchases","LOG_LEVEL":"INFO","MONGODB_COLLECTION":"purchases","MONGODB_DB_NAME":"ecommerce","MONGODB_URI":"mongodb://mongodb-service:27017"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"ecommerce"},"name":"app-config","namespace":"ecommerce-system"}}
  creationTimestamp: "2025-12-16T08:39:51Z"
  labels:
    app: ecommerce
  name: app-config
  namespace: ecommerce-system
  resourceVersion: "2662"
  uid: 28c4aebb-694c-4409-96ed-006141f04164
